version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install black
      - run: black .

workflows:
  version: 2
  quality-check:
    jobs:
      - test
      - lint